/***
 * Created by Darcy
 * Github: https://github.com/Darcy97
 * Date: Monday, 28 June 2021
 * Time: 21:02:20
 * Description:
 * è¯¥è„šæœ¬çš„ç”±æ¥
 * å½“æ—¶ç¾æœ¯æœ‰ä¸€ä¸ªéœ€æ±‚æƒ³è¦é€šè¿‡åŠ¨ç”» Animation åŠ¨æ€æ§åˆ¶æè´¨çƒçš„å±æ€§
 * ä½†æ˜¯ Unity ä¸æ”¯æŒï¼ˆ2018.4.27)
 * æ‰€ä»¥æƒ³åˆ°é€šè¿‡è„šæœ¬æ¥æ§åˆ¶ï¼Œç„¶ååŠ¨ç”»æ¥æ§åˆ¶è„šæœ¬çš„å‚æ•°
 * å½“æ—¶ä¸ºäº†æƒ³è¦è„šæœ¬é€šç”¨æ€§æ›´é«˜ï¼Œå¯ä»¥é€šè¿‡ç®€å•é…ç½® Inspector æ¥é€‚é…æ‰€æœ‰æè´¨
 * æ‰€ä»¥å¼€å‘äº†è¯¥è„šæœ¬
 * ä½†æ˜¯æ— å¥ˆï¼ŒUnity animation åªèƒ½æ§åˆ¶è„šæœ¬çš„å˜é‡ï¼Œåƒè¿™ç§ List é‡Œé¢çš„å˜é‡å¯¹è±¡çš„å€¼ Animation è®°å½•ä¸äº†
 * é‚ï¼Œè¯¥è„šæœ¬å‘¢æœ€åæ²¡æœ‰äº§ç”Ÿç”Ÿäº§ä»·å€¼ï¼Œä½†æ˜¯è¿™è¿‡ç¨‹ä¸­ç ”ç©¶äº†ä¸€äº› PropertyDrawer æ‰€ä»¥ä¹Ÿä¸ç®—åšæ— ç”¨åŠŸ ğŸ˜„
 * æœ€ç»ˆæŠ•å…¥ä½¿ç”¨çš„è„šæœ¬åœ¨å¦ä¸€ä¸ªç›®å½•ä¸‹: AnimatorMaterialBase é€šç”¨æ€§ä¸æ˜¯å¾ˆé«˜ï¼Œä½†æ˜¯ç¬¦åˆå®é™…éœ€æ±‚ï¼Œå› ä¸ºç¾æœ¯åŒå­¦ä¹Ÿåªæ˜¯éœ€è¦å‡ ä¸ªæè´¨åšè¿™ä¸ªå¤„ç†ï¼ˆå®é™…å¥½åƒåªæœ‰ä¸€ä¸ªæè´¨ç”¨äº†ã€‚ã€‚ã€‚)
 ***/

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace DarcyStudio.CustomEditor.ExploreForPropertyDrawer.ModifyKeyValueProperty
{

    [ExecuteInEditMode]
    public class AnimatorMaterial : MonoBehaviour
    {

        [SerializeField] private Material _material;

        [SerializeField] private List<ModifyKeyValue> _modifyValues;

        private bool _isValid;

        private void Awake ()
        {
            Init ();
        }

        private void Init ()
        {
            var render = GetComponent<Image> ();
            if (render == null)
            {
                Debug.LogError ("AnimatorMaterial -->> No Renderer Component");
                return;
            }

            _material = render.material;

            InitModify ();

            _isValid = true;
        }

        private void InitModify ()
        {
            foreach (var item in _modifyValues)
            {
                if (item == null)
                    continue;

                item.Init ();

                var hasProperty = _material.HasProperty (item.KeyID);
                if (hasProperty)
                    continue;
                Debug.LogError ("AnimatorMaterial -->> Invalid Property: " + item.Key);
                item.SetInvalid ();
            }
        }

        private void LateUpdate ()
        {
            if (!_isValid)
                return;
            UpdateMaterial ();
        }

        private void UpdateMaterial ()
        {
            foreach (var item in _modifyValues)
            {
                if (item == null)
                    continue;
                if (!item.IsValid)
                    continue;

                switch (item.ModifyValueType)
                {
                    case ModifyValueType.TypeInt:
                        _material.SetInt (item.KeyID, item.IntValue);
                        break;
                    case ModifyValueType.TypeFloat:
                        _material.SetFloat (item.KeyID, item.FloatValue);
                        break;
                    case ModifyValueType.TypeColor:
                        _material.SetColor (item.KeyID, item.ColorValue);
                        break;
                    case ModifyValueType.Default:
                        Debug.LogError ("AnimatorMaterial -->> Un Handle type: " + item.ModifyValueType);
                        break;
                    default:
                        Debug.LogError ("AnimatorMaterial -->> Un Handle type" + item.ModifyValueType);
                        break;
                }
            }
        }

        public void DrawButtons ()
        {

            if (GUILayout.Button ("ReInit"))
            {
                Init ();
            }
        }
    }
    
    
   
}